### ISSUE TITLE
Updating original Google Code site

### ISSUE THREAD

**Issue by unwiredben** [sirleech/Webduino#12]
I just updated the main page on the Google Code site to note that 1.6 is available here and that this is the main branch for future development.  I was wondering if we should move open issues from GC over to the issues tracker here.

**Comment by tfnab** [comment]
Hi Ben,

Yes. I'm in favor of moving open issues over here. I have already commented on some of the threads on Google Code. Can you close them or at least update the status to make this move transparent?

Cheers,
Martin

**Comment by unwiredben** [comment]
OK, I'm closing a bunch of issues, looking at pushing fixes for a few of the others, and will re-file any other open ones here.
