### ISSUE TITLE
webduino on codebender

### ISSUE THREAD

**Issue by tzikis** [sirleech/Webduino#19]
Hi, I'm Vasilis Georgitzikis from the codebender team. This isn't an Issue with webduino, but I couldn't find a better way to contact you.

In case you haven't heard, codebender is a web platform (including an Arduino IDE) that allows you to code faster and easier through the browser. One of the important features is our ability to remotely program an Arduino /w Ethernet shield of Arduino Ethernet through the network!

I'm writing to notify you that we'll include the webduino library in the list of pre-installed libraries, since I use it extensively and I find it very valuable. Big congrats on that! You might also be interested in trying out codebender. We are currently in closed beta, but I can create an account for you if you're interested.

**Comment by unwiredben** [comment]
Great! I'll send an email.

**Comment by ronnqvist** [comment]
I'd be very much interested in your project. Please create an account for simon@iki.fi
Thanks!

  cheers, Simon

Vasilis Georgitzikis reply@reply.github.com skrev:

**Comment by tzikis** [comment]
Hi Simon.
Please preregister at http://codebender.cc with this email and i'll add you to the next batch of people we'll invite.

Regards,
Vasilis

**Comment by ronnqvist** [comment]
Done, thanks!

Vasilis Georgitzikis reply@reply.github.com skrev:

**Comment by sirleech** [comment]
Thanks. Actually I can't take credit, this is Ben Combee's work.

Chris Lee
Australian Robotics
On Jul 18, 2012 11:25 PM, "Vasilis Georgitzikis" <
reply@reply.github.com>
wrote:
