### ISSUE TITLE
httpSuccess() extraHeaders when used causes no response body to show

### ISSUE THREAD

**Issue by sirleech** [sirleech/Webduino#2]

**Comment by gfoiani** [comment]
Try substituting in the file WebServer.cpp (at lines 266-267):

 if (extraHeaders)
    print(extraHeaders);

with the following code:

 if (extraHeaders) {
    print(extraHeaders);
    printCRLF();
}

HTTP Responses needs to end with double CRLF.
For me it works.

Giovanni

**Comment by sirleech** [comment]
Committed the above fix. Thanks Giovanni.

**Comment by tfnab** [comment]
I reverted this in 1711391319cf3b62d3c3bf09e964ae88acaed8b1

Extra headers should always be terminated with CRLF.
