### ISSUE TITLE
SSL support now possible?

### ISSUE THREAD

**Issue by traumatic** [sirleech/Webduino#29]
Hi there, would the Arduino Duo provide enough power for SSL support? Would be great if SSL is supported in future. Keep up the great work!

**Comment by unwiredben** [comment]
The smallest open source library that I can see for SSL is yaSSL (http://www.yassl.com/yaSSL/Home.html), which compiles to 30-100K of binary code and uses up to 36K of memory.  The Arduino Due board is fast enough (84MHz) and has enough flash (512K) to support this.  Memory may be tight, as it only has 96K.  However, I'm not planning on working on this -- I don't have a Due board and I feel like a Raspberry Pi is much more cost effective, as it has more memory, it's faster, and it runs Linux where you can run a standard web server stack without needing a lot of new development.  You can get a Pi for less than half the cost of a Due + Ethernet Shield.

**Comment by traumatic** [comment]
Hi Ben, that makes sense. However the Pi audience is different compared to the Arduino hobby electronic enthusiasts. Hey, I'll buy you a Due and you'll add yassl to Webduino ;-)

**Comment by ronnqvist** [comment]
Hi! I must say that I partially disagree with you. Of course the 
Raspberry Pi has other application than electronics, but when playing 
with electronics I'd say it has pretty much the same audience. Arduinos 
have been around longer and thus have more libraries and related 
hardware out there, but as time passes by the Pi will have that too. Of 
course for some simple projects the Pi would be overkill, for some even 
the Arduino is (if you know how to program simpler/cheaper 
microcontrollers).

However, when it comes to web/networking-related projects the Pi is 
certainly more capable. Ie. for the RGB-led examples that I made for 
Webduino I had a hard time keeping the browser from DDoS:ing the 
Arduino. :) Of course Arduinos develop and become more capable too, 
it'll be interesting to see what things are best used for what in a 
couple of years. For the time being you can get a Gertboard and have a 
Raspberry Pi and an Arduino combined, or whatever floats your boat.

**Comment by unwiredben** [comment]
I'd say that if I was porting yaSSL to Webduino, i'd probably just port the whole yaSSL embedded web server (http://www.yassl.com/yaSSL/Products-yassl-embedded-web-server.html).  One problem with adding a whole stack like this is you then need some sort of RTOS to handle multitasking between the real-time signal control parts of your code and the web server code, since the server can add a lot of latency to handling incoming signals if run in a single-task mode.

Alas, I'm too busy right now to even do much with the original Webduino code :(
