### ISSUE TITLE
Change owner of this repository to unwired_ben? (original author)

### ISSUE THREAD

**Issue by sirleech** [sirleech/Webduino#32]
Hi Ben,

Would you like to take back ownership of this repository? It is your baby after all!

**Comment by unwiredben** [comment]
Yeah, I'd love to do that, but I want to make sure you're on the commit list.  I have my own fork, but it has no new development on it, so I should be able to just delete it before you change owners.

**Comment by sirleech** [comment]
OK. Let me know, and I'm happy to keep this repository.

On Fri, Mar 1, 2013 at 8:07 AM, Ben Combee notifications@github.com wrote:

> Yeah, I'd love to do that, but I want to make sure you're on the commit
> list. I have my own fork, but it has no new development on it, so I should
> be able to just delete it before you change owners.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sirleech/Webduino/issues/32#issuecomment-14257619
> .

## 

Best wishes,

Christopher Lee
AustralianRobotics.com.au http://australianrobotics.com.au/

Australian Robotics Pty Ltd
GPO Box 1139
Canberra, ACT 2601
Australia

ABN: 71 155 712 422

**Comment by unwiredben** [comment]
I've created a "Webduino" organization to hold this repo -- if you want to move it to there, I've made you a co-owner of the org.

https://github.com/webduino

**Comment by unwiredben** [comment]
I've moved my own "unwiredben" fork into the webuino repo, it's now https://github.com/webduino/Webduino
