### ISSUE TITLE
Port to SAM3X8E (Ardunio Due)

### ISSUE THREAD

**Issue by jupp0r** [sirleech/Webduino#37]
The library should be ported to support the new Arduino platforms like Arduino Due.

**Comment by jupp0r** [comment]
The main part should be removing PROGMEM, etc, that are not needed for the ARM.

**Comment by unwiredben** [comment]
This work will need to be done with someone with one of the new boards.  I'm not planning on getting one.

**Comment by unwiredben** [comment]
Awesome, get to close this one.
