### ISSUE TITLE
Please split into .h and .cpp for easier integration in other libraries

### ISSUE THREAD

**Issue by cyberwaelder** [sirleech/Webduino#4]

**Comment by sirleech** [comment]
Hi @cyberwaelder,

Would you be interested in participating in this project? Feel free to
fork the code and we can pull your changes when ready.

I don't plan in working on Webserver.h anytime in the near future (I'm
playing with clients ATM) so we shouldn't conflict.

Cheers,

Christopher Lee
www.AustralianRobotics.com.au
Australian Robotics

On 11/07/2011, at 1:21 AM, cyberwaelder
reply@reply.github.com
wrote:

**Comment by cyberwaelder** [comment]
Hi Christopher,

that sounds good. I fork the code the next days and split Webserver.h.

Thanks

**Comment by sirleech** [comment]
I'll keep it open as you're working on it :)

**Comment by cyberwaelder** [comment]
I can't send a pull request. I always get an error.

**Comment by sirleech** [comment]
Hi cyberwaelder,

Can you please send me the URL of your git hub repo.

Cheers,

Christopher Lee
www.AustralianRobotics.com.au
Australian Robotics

On 14/07/2011, at 5:46 AM, cyberwaelder
reply@reply.github.com
wrote:

**Comment by cyberwaelder** [comment]
https://github.com/cyberwaelder/Webduino
