### ISSUE TITLE
timeout / DOS

### ISSUE THREAD

**Issue by gpothier** [sirleech/Webduino#43]
Hi, it seems the WEBDUINO_READ_TIMEOUT_IN_MS parameter is not effective in preventing DOS against Webduino: currently I can open a connection to Webduino, and maintain it open as long as I want without sending any request, thus preventing other connections from being processed. 
Looking at the current implementation of the read() method, the only way a timeout could occur would be if the m_client.read() call took more time than the timeout, but this never happens as m_client.read() just returns -1 if there is nothing to read. Thus timeout never occurs.
As I see it, to make timeout working we would need to store the timestamp of the last successful read (or initially of the initiation of the connection) in the WebServer object, and check if we exceeded the timeout at each read() call. I can do the change and send a patch if you think this is the correct solution.

**Comment by gpothier** [comment]
Ok, I didn't understand the Webduino code well enough. The issue is at another level (Wiznet chip or Ethernet library): if I establish 4 connections to the Arduino without sending any data, Webduino never knows about the connections, but the Arduino cannot accept any more connections, resulting in a DOS.

**Comment by unwiredben** [comment]
Yeah -- if you're running a public-facing web service off an Arduino, you're in a world of pain.  It's much better in that case to use a ARM-based Linux board like a BeagleBone or Raspberry Pi for that setup.

**Comment by gpothier** [comment]
In my case it is not public facing, but I still was able to have it stuck with idle connections (I actually don't know why). I'm writing a bit of code to check for and drop idle connections at the Ethernet library level. I can post it here if it is of interest.

**Comment by DonKnowlton** [comment]
I would like to try your code to drop idle connections.  Please post it.

Thanks

**Comment by gpothier** [comment]
Not much luck yet... without modifying the original Ethernet library, it seems the only thing I can do is forcefully close all connections (regardless of whether they are idle or not) at some interval... I'm still trying to find a better way.
