### ISSUE TITLE
Changes required for Arduino-1.0

### ISSUE THREAD

**Issue by railnerd** [sirleech/Webduino#7]
Been playing with arduino-1.0-rc1, and had to make the following patches to get your code working in the 1.0 release.

Hope this helps,

 railnerd@me.com

diff --git a/WebServer.cpp b/WebServer.cpp
index 5d9a88d..a781d8b 100644
--- a/WebServer.cpp
+++ b/WebServer.cpp
@@ -60,24 +60,24 @@ void WebServer::addCommand(const char *verb, Command *cmd)
   }
 }

-void WebServer::write(uint8_t ch)
+size_t WebServer::write(uint8_t ch)
 {
-  m_client.write(ch);
-  return m_client.write(ch);
  }

-void WebServer::write(const char *str)
+size_t WebServer::write(const char *str)
 {
-  m_client.write(str);
-  return m_client.write(str);
  }

-void WebServer::write(const uint8_t *buffer, size_t size)
+size_t WebServer::write(const uint8_t *buffer, size_t size)
 {
-  m_client.write(buffer, size);
-  return m_client.write(buffer, size);
  }

-void WebServer::write(const char *buffer, size_t length)
+size_t WebServer::write(const char *buffer, size_t length)
 {
-  m_client.write((const uint8_t *)buffer, length);
-  return m_client.write((const uint8_t *)buffer, length);
  }
  
  void WebServer::writeP(const prog_uchar *data, size_t length)
  diff --git a/WebServer.h b/WebServer.h
  index bdcd614..4879f44 100644
  --- a/WebServer.h
  +++ b/WebServer.h
  @@ -29,8 +29,8 @@
  # include <stdlib.h>
  # include "avr/pgmspace.h"

-#include <Client.h>
-#include <Server.h>
+#include <EthernetClient.h>
+#include <EthernetServer.h>

 /********************************************************************
- CONFIGURATION
  @@ -200,14 +200,14 @@ public:
  void httpSeeOther(const char *otherURL);
  
  // implementation of write used to implement Print interface
  -  virtual void write(uint8_t);
  -  virtual void write(const char *str);
  -  virtual void write(const uint8_t *buffer, size_t size);
  -  void write(const char *data, size_t length);
  -  virtual size_t write(uint8_t);
  -  virtual size_t write(const char *str);
  -  virtual size_t write(const uint8_t *buffer, size_t size);
  -  size_t write(const char *data, size_t length);
  
  private:
  -  Server m_server;
  -  Client m_client;
  -  EthernetServer m_server;
  -  EthernetClient m_client;
    const char *m_urlPrefix;
  
  char m_pushback[32];

**Comment by sirleech** [comment]
Hi Railnerd,

Thanks for your contribution. Honestly I haven't used 1.0 yet, is it a new
bootloader or IDE?

On Fri, Sep 23, 2011 at 4:53 PM, railnerd <
reply@reply.github.com>wrote:

> Been playing with arduino-1.0-rc1, and had to make the following patches to
> get your code working in the 1.0 release.
> 
> Hope this helps,
> 
>  railnerd@me.com
> 
> diff --git a/WebServer.cpp b/WebServer.cpp
> index 5d9a88d..a781d8b 100644
> --- a/WebServer.cpp
> +++ b/WebServer.cpp
> @@ -60,24 +60,24 @@ void WebServer::addCommand(const char *verb, Command
> *cmd)
>   }
>  }
> 
> -void WebServer::write(uint8_t ch)
> +size_t WebServer::write(uint8_t ch)
>  {
> -  m_client.write(ch);
> -  return m_client.write(ch);
>   }
> 
> -void WebServer::write(const char *str)
> +size_t WebServer::write(const char *str)
>  {
> -  m_client.write(str);
> -  return m_client.write(str);
>   }
> 
> -void WebServer::write(const uint8_t *buffer, size_t size)
> +size_t WebServer::write(const uint8_t *buffer, size_t size)
>  {
> -  m_client.write(buffer, size);
> -  return m_client.write(buffer, size);
>   }
> 
> -void WebServer::write(const char *buffer, size_t length)
> +size_t WebServer::write(const char *buffer, size_t length)
>  {
> -  m_client.write((const uint8_t *)buffer, length);
> -  return m_client.write((const uint8_t *)buffer, length);
>   }
>   
>   void WebServer::writeP(const prog_uchar *data, size_t length)
>   diff --git a/WebServer.h b/WebServer.h
>   index bdcd614..4879f44 100644
>   --- a/WebServer.h
>   +++ b/WebServer.h
>   @@ -29,8 +29,8 @@
>   #include <stdlib.h>
>   #include "avr/pgmspace.h"
> 
> -#include <Client.h>
> -#include <Server.h>
> +#include <EthernetClient.h>
> +#include <EthernetServer.h>
> 
>  /********************************************************************
> - CONFIGURATION
>   @@ -200,14 +200,14 @@ public:
>   void httpSeeOther(const char *otherURL);
>   
>   // implementation of write used to implement Print interface
>   -  virtual void write(uint8_t);
>   -  virtual void write(const char *str);
>   -  virtual void write(const uint8_t *buffer, size_t size);
>   -  void write(const char *data, size_t length);
>   -  virtual size_t write(uint8_t);
>   -  virtual size_t write(const char *str);
>   -  virtual size_t write(const uint8_t *buffer, size_t size);
>   -  size_t write(const char *data, size_t length);
>   
>   private:
>   -  Server m_server;
>   -  Client m_client;
>   -  EthernetServer m_server;
>   -  EthernetClient m_client;
>     const char *m_urlPrefix;
>   
>   char m_pushback[32];
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sirleech/Webduino/issues/7

## 

Christopher Lee
Canberra, Australia
+61 0404214644

**Comment by railnerd** [comment]
IDE + library changes.

Was just hacking something playing with the new IDE, and after I found and fixed one of the other IDE bugs, I tried recompiling my web server sketch that leveraged your code.  Then I discovered they had refactored the Ethernet library (in prep for their WiFi shield)

I guess the 1.0 release is in about a month, but the release candidates can be found here:

```
http://bit.ly/arduino1
```

Thanks,

-Dave

Railnerd refers to my late night model train hacking...

My day job is at a big company in Cupertino, so I keep work  completely separate from home hacking, hence the goofy email.

**Comment by sirleech** [comment]
Thanks for the link-- I had a look on arduino.cc, and it doesn't look it
it's there yet. Do you think the 1.0-RC1 is stable enough to commit your
patch to the master branch of sirleech/Webduino?

I'm also happy for you to make a new "dev" branch and commit your changes to
sirleech/Webduino. I can add you as a contributor to the repository if
you're interested :)

On Sat, Sep 24, 2011 at 11:32 AM, railnerd <
reply@reply.github.com>wrote:

> IDE + library changes.
> 
> Was just hacking something playing with the new IDE, and after I found and
> fixed one of the other IDE bugs, I tried recompiling my web server sketch
> that leveraged your code.  Then I discovered they had refactored the
> Ethernet library (in prep for their WiFi shield)
> 
> I guess the 1.0 release is in about a month, but the release candidates can
> be found here:
> 
>    http://bit.ly/arduino1
> 
> Thanks,
> 
> -Dave
> 
> Railnerd refers to my late night model train hacking...
> 
> My day job is at a big company in Cupertino, so I keep work  completely
> separate from home hacking, hence the goofy email.
> 
> On Sep 23, 2011, at 4:53 PM, Christopher Leereply@reply.github.com
> wrote:
> 
> > Hi Railnerd,
> > 
> > Thanks for your contribution. Honestly I haven't used 1.0 yet, is it a
> > new
> > bootloader or IDE?
> > 
> > On Fri, Sep 23, 2011 at 4:53 PM, railnerd <
> > reply@reply.github.com>wrote:
> > 
> > > Been playing with arduino-1.0-rc1, and had to make the following patches
> > > to
> > > get your code working in the 1.0 release.
> > > 
> > > Hope this helps,
> > > 
> > > railnerd@me.com
> > > 
> > > diff --git a/WebServer.cpp b/WebServer.cpp
> > > index 5d9a88d..a781d8b 100644
> > > --- a/WebServer.cpp
> > > +++ b/WebServer.cpp
> > > @@ -60,24 +60,24 @@ void WebServer::addCommand(const char *verb, Command
> > > *cmd)
> > >  }
> > > }
> > > 
> > > -void WebServer::write(uint8_t ch)
> > > +size_t WebServer::write(uint8_t ch)
> > > {
> > > -  m_client.write(ch);
> > > -  return m_client.write(ch);
> > >   }
> > > 
> > > -void WebServer::write(const char *str)
> > > +size_t WebServer::write(const char *str)
> > > {
> > > -  m_client.write(str);
> > > -  return m_client.write(str);
> > >   }
> > > 
> > > -void WebServer::write(const uint8_t *buffer, size_t size)
> > > +size_t WebServer::write(const uint8_t *buffer, size_t size)
> > > {
> > > -  m_client.write(buffer, size);
> > > -  return m_client.write(buffer, size);
> > >   }
> > > 
> > > -void WebServer::write(const char *buffer, size_t length)
> > > +size_t WebServer::write(const char *buffer, size_t length)
> > > {
> > > -  m_client.write((const uint8_t *)buffer, length);
> > > -  return m_client.write((const uint8_t *)buffer, length);
> > >   }
> > > 
> > > void WebServer::writeP(const prog_uchar *data, size_t length)
> > > diff --git a/WebServer.h b/WebServer.h
> > > index bdcd614..4879f44 100644
> > > --- a/WebServer.h
> > > +++ b/WebServer.h
> > > @@ -29,8 +29,8 @@
> > > #include <stdlib.h>
> > > #include "avr/pgmspace.h"
> > > 
> > > -#include <Client.h>
> > > -#include <Server.h>
> > > +#include <EthernetClient.h>
> > > +#include <EthernetServer.h>
> > > 
> > > /********************************************************************
> > > - CONFIGURATION
> > >   @@ -200,14 +200,14 @@ public:
> > >   void httpSeeOther(const char *otherURL);
> > >   
> > >   // implementation of write used to implement Print interface
> > > -  virtual void write(uint8_t);
> > > -  virtual void write(const char *str);
> > > -  virtual void write(const uint8_t *buffer, size_t size);
> > > -  void write(const char *data, size_t length);
> > > -  virtual size_t write(uint8_t);
> > > -  virtual size_t write(const char *str);
> > > -  virtual size_t write(const uint8_t *buffer, size_t size);
> > > -  size_t write(const char *data, size_t length);
> > > 
> > > private:
> > > -  Server m_server;
> > > -  Client m_client;
> > > -  EthernetServer m_server;
> > > -  EthernetClient m_client;
> > >   const char *m_urlPrefix;
> > >   
> > >   char m_pushback[32];
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/sirleech/Webduino/issues/7
> > 
> > ## 
> > 
> > Christopher Lee
> > Canberra, Australia
> > +61 0404214644
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/sirleech/Webduino/issues/7#issuecomment-2183973
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sirleech/Webduino/issues/7#issuecomment-2184410

## 

Christopher Lee
Canberra, Australia
+61 0404214644

**Comment by railnerd** [comment]
I think a 1.0rc1 branch is probably good for now.  Once 1.0 actually goes out, you can push it up to master.

-Dave

**Comment by sirleech** [comment]
Hi Dave,

Had a quick try to apply the patch, but getting these errors:

error: patch failed: WebServer.cpp:60
error: WebServer.cpp: patch does not apply
error: patch failed: WebServer.h:29
error: WebServer.h: patch does not apply

Could you perhaps send me a patch file, or push to your own Git Repo so I
can make a pull?

On Fri, Sep 23, 2011 at 4:53 PM, railnerd <
reply@reply.github.com>wrote:

> Been playing with arduino-1.0-rc1, and had to make the following patches to
> get your code working in the 1.0 release.
> 
> Hope this helps,
> 
>  railnerd@me.com
> 
> diff --git a/WebServer.cpp b/WebServer.cpp
> index 5d9a88d..a781d8b 100644
> --- a/WebServer.cpp
> +++ b/WebServer.cpp
> @@ -60,24 +60,24 @@ void WebServer::addCommand(const char *verb, Command
> *cmd)
>   }
>  }
> 
> -void WebServer::write(uint8_t ch)
> +size_t WebServer::write(uint8_t ch)
>  {
> -  m_client.write(ch);
> -  return m_client.write(ch);
>   }
> 
> -void WebServer::write(const char *str)
> +size_t WebServer::write(const char *str)
>  {
> -  m_client.write(str);
> -  return m_client.write(str);
>   }
> 
> -void WebServer::write(const uint8_t *buffer, size_t size)
> +size_t WebServer::write(const uint8_t *buffer, size_t size)
>  {
> -  m_client.write(buffer, size);
> -  return m_client.write(buffer, size);
>   }
> 
> -void WebServer::write(const char *buffer, size_t length)
> +size_t WebServer::write(const char *buffer, size_t length)
>  {
> -  m_client.write((const uint8_t *)buffer, length);
> -  return m_client.write((const uint8_t *)buffer, length);
>   }
>   
>   void WebServer::writeP(const prog_uchar *data, size_t length)
>   diff --git a/WebServer.h b/WebServer.h
>   index bdcd614..4879f44 100644
>   --- a/WebServer.h
>   +++ b/WebServer.h
>   @@ -29,8 +29,8 @@
>   #include <stdlib.h>
>   #include "avr/pgmspace.h"
> 
> -#include <Client.h>
> -#include <Server.h>
> +#include <EthernetClient.h>
> +#include <EthernetServer.h>
> 
>  /********************************************************************
> - CONFIGURATION
>   @@ -200,14 +200,14 @@ public:
>   void httpSeeOther(const char *otherURL);
>   
>   // implementation of write used to implement Print interface
>   -  virtual void write(uint8_t);
>   -  virtual void write(const char *str);
>   -  virtual void write(const uint8_t *buffer, size_t size);
>   -  void write(const char *data, size_t length);
>   -  virtual size_t write(uint8_t);
>   -  virtual size_t write(const char *str);
>   -  virtual size_t write(const uint8_t *buffer, size_t size);
>   -  size_t write(const char *data, size_t length);
>   
>   private:
>   -  Server m_server;
>   -  Client m_client;
>   -  EthernetServer m_server;
>   -  EthernetClient m_client;
>     const char *m_urlPrefix;
>   
>   char m_pushback[32];
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sirleech/Webduino/issues/7

## 

Christopher Lee
Canberra, Australia
+61 0404214644

**Comment by railnerd** [comment]
Sure.  Will probably do that tonight.

**Comment by railnerd** [comment]
here you go...

https://github.com/railnerd/Webduino

**Comment by sirleech** [comment]
Thanks. Pulled into sirleech/Webduino/1.0rc1

On Tue, Sep 27, 2011 at 10:33 AM, railnerd <
reply@reply.github.com>wrote:

> here you go...
> 
> https://github.com/railnerd/Webduino
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sirleech/Webduino/issues/7#issuecomment-2205819

## 

Christopher Lee
Canberra, Australia
+61 0404214644
