### ISSUE TITLE
Split library?

### ISSUE THREAD

**Issue by kjetilk** [sirleech/Webduino#75]
I'm playing around with implementing parts of the new [Web-of-Things specs](https://w3c.github.io/wot-thing-description/) and HTML is therefore not something I would serve. I was therefore thinking it may make sense to split this library into parts, where the protocol stuff is in one library, and the HTML stuff is in another, as these are orthogonal issues?

**Comment by unwiredben** [comment]
Feel free to fork the library as you wish.  Webduino is pretty dead as far
as development, so if you do that, please rename it.

**Comment by kjetilk** [comment]
OK, thanks a lot, I'll consider that!
